
package com.javacodegeeks.examples.jaxws.client;

import java.util.concurrent.Future;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.AsyncHandler;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.Response;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ChangeMessage", targetNamespace = "http://service.jaxws.examples.javacodegeeks.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ChangeMessage {


    /**
     * 
     * @param arg0
     * @return
     *     returns javax.xml.ws.Response<com.javacodegeeks.examples.jaxws.client.TestMessage>
     */
    @WebMethod(operationName = "changeMessage")
    @RequestWrapper(localName = "changeMessage", targetNamespace = "http://service.jaxws.examples.javacodegeeks.com/", className = "com.javacodegeeks.examples.jaxws.client.ChangeMessage_Type")
    @ResponseWrapper(localName = "changeMessageResponse", targetNamespace = "http://service.jaxws.examples.javacodegeeks.com/", className = "com.javacodegeeks.examples.jaxws.client.TestMessage")
    public Response<TestMessage> changeMessageAsync(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @param asyncHandler
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "changeMessage")
    @RequestWrapper(localName = "changeMessage", targetNamespace = "http://service.jaxws.examples.javacodegeeks.com/", className = "com.javacodegeeks.examples.jaxws.client.ChangeMessage_Type")
    @ResponseWrapper(localName = "changeMessageResponse", targetNamespace = "http://service.jaxws.examples.javacodegeeks.com/", className = "com.javacodegeeks.examples.jaxws.client.TestMessage")
    public Future<?> changeMessageAsync(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "asyncHandler", targetNamespace = "")
        AsyncHandler<TestMessage> asyncHandler);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "message", targetNamespace = "")
    @RequestWrapper(localName = "changeMessage", targetNamespace = "http://service.jaxws.examples.javacodegeeks.com/", className = "com.javacodegeeks.examples.jaxws.client.ChangeMessage_Type")
    @ResponseWrapper(localName = "changeMessageResponse", targetNamespace = "http://service.jaxws.examples.javacodegeeks.com/", className = "com.javacodegeeks.examples.jaxws.client.TestMessage")
    public String changeMessage(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
